name: Bonjour
on:
  - push
jobs:
  node_test:
    runs-on: ubuntu-22.04
    env: 
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4
      - run: docker image build --tag="${IMAGE_NAME}" .
      - run: pwd
      - run: ls -la
      - run: docker container run --workdir="$(pwd)" --volume="$(pwd)/index.js:$(pwd)/index.js" "${IMAGE_NAME}" npm run lint